# Generated by Django 4.2.5 on 2023-10-12 20:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bldg_name', models.CharField(max_length=50)),
                ('bldg_type', models.CharField(choices=[('Academic', 'Academic'), ('StudentCenter', 'Student Center')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_number', models.IntegerField(max_length=4)),
                ('course_name', models.CharField(max_length=50)),
                ('no_of_credits', models.IntegerField()),
                ('description', models.TextField()),
                ('course_type', models.CharField(choices=[('UnderGrad', 'Undergraduate'), ('Grad', 'Graduate')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=10)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.building')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=20)),
                ('semester_year', models.IntegerField()),
                ('start_date', models.DateField(default='2000-01-01')),
                ('end_date', models.DateField(default='2000-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('dob', models.DateField(default='2000-01-01')),
                ('street', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=10, null=True)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Student', 'Student'), ('Faculty', 'Faculty')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.user')),
                ('access_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.user')),
                ('rank', models.CharField(choices=[('Prof', 'Professor'), ('AsstProf', 'Assistant Professor'), ('Adjunct', 'Adjunct'), ('TA', 'Teaching Assistant')], max_length=8)),
                ('specialty', models.CharField(max_length=50)),
                ('fac_type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.room')),
                ('no_of_workstations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.room')),
                ('no_of_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsOffice',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.user')),
                ('access_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.user')),
                ('studentID', models.IntegerField(blank=True, null=True, unique=True)),
                ('student_year', models.IntegerField(null=True)),
                ('student_type', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ManyToManyField(to='registration.day')),
                ('periods', models.ManyToManyField(to='registration.period')),
            ],
        ),
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minor_name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.department')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='room_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.room'),
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('crn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('available_seats', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.course')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.room')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.semester')),
                ('timeslot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePrereq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_grade', models.CharField(max_length=2)),
                ('date_of_last_update', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='registration.course')),
                ('pr_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_course', to='registration.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.department'),
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('no_of_attempts', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.student')),
                ('program', models.CharField(choices=[('Masters', 'Masters'), ('PHD', 'PHD')], max_length=7)),
                ('grad_student_type', models.CharField(choices=[('FullTime', 'Full-Time'), ('PartTime', 'Part-Time')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Undergraduate',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.student')),
                ('undergrad_student_type', models.CharField(choices=[('FullTime', 'Full-Time'), ('PartTime', 'Part-Time')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.coursesection')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='major_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.major'),
        ),
        migrations.AddField(
            model_name='student',
            name='minor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.minor'),
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_type', models.CharField(choices=[('Financial', 'Financial'), ('Academic', 'Academic'), ('Health', 'Health'), ('Disciplinary', 'Disciplinary')], max_length=15)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.student')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.coursesection')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.semester')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.department'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('date_of_enrollment', models.DateField()),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.coursesection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.student')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='chair_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chair', to='registration.faculty'),
        ),
        migrations.AddField(
            model_name='department',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to='registration.faculty'),
        ),
        migrations.AddField(
            model_name='coursesection',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.faculty'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_class', models.DateField()),
                ('present', models.BooleanField()),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.coursesection')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.student')),
            ],
        ),
        migrations.CreateModel(
            name='Grad_Full_Time',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.graduate')),
                ('year', models.IntegerField(default=2023)),
                ('credits_earned', models.IntegerField(default=0)),
                ('qualifying_exam', models.BooleanField(default=False)),
                ('thesis', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Grad_Part_Time',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.graduate')),
                ('year', models.IntegerField(default=2023)),
                ('credits_earned', models.IntegerField(default=0)),
                ('qualifying_exam', models.BooleanField(default=False)),
                ('thesis', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Undergrad_Full_Time',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.undergraduate')),
                ('standing', models.CharField(choices=[('Fresh', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=10)),
                ('min_creds', models.IntegerField(default=12)),
                ('max_creds', models.IntegerField(default=18)),
                ('creds_earned', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Undergrad_Part_Time',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.undergraduate')),
                ('standing', models.CharField(choices=[('Fresh', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=10)),
                ('min_creds', models.IntegerField(default=4)),
                ('max_creds', models.IntegerField(default=11)),
                ('creds_earned', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='undergraduate',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.department'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.department'),
        ),
        migrations.CreateModel(
            name='Faculty_PartTime',
            fields=[
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.faculty')),
                ('num_of_courses', models.IntegerField(default=1)),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.room')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_FullTime',
            fields=[
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.faculty')),
                ('num_of_courses', models.IntegerField(default=2)),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.room')),
            ],
        ),
    ]
