# Generated by Django 4.2.5 on 2023-10-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_year',
            new_name='enrollment_year',
        ),
    ]
