# Generated by Django 4.2.5 on 2023-10-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_room_options_alter_course_course_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building__bldg_name', 'room_no']},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
