# Generated by Django 4.2.5 on 2023-11-07 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_room_options_alter_course_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='class_obj',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='class_obj',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='facultyhistory',
            old_name='class_obj',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='studenthistory',
            old_name='class_obj',
            new_name='section',
        ),
    ]
