# Generated by Django 4.2.5 on 2023-11-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_rename_class_obj_attendance_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='department',
        ),
        migrations.AddField(
            model_name='faculty',
            name='departments',
            field=models.ManyToManyField(to='registration.department'),
        ),
    ]
