# Generated by Django 4.2.5 on 2023-11-13 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_faculty_department_faculty_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyhistory',
            name='course',
        ),
    ]
