# Generated by Django 4.2.5 on 2023-11-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_facultyhistory_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='fac_type',
            field=models.CharField(choices=[('FullTime', 'Full-Time'), ('PartTime', 'Part-Time')], max_length=8),
        ),
    ]
