# Generated by Django 4.2.5 on 2023-11-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_faculty_fac_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='rank',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Assistant Professor', 'Assistant Professor'), ('Adjunct Professor', 'Adjunct'), ('Teaching Assistant', 'Teaching Assistant')], max_length=24),
        ),
    ]
