# Generated by Django 4.2.5 on 2023-11-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_remove_attendance_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='specialty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='MinorDegreeRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_required', models.IntegerField()),
                ('courses', models.ManyToManyField(blank=True, related_name='minor_courses', to='registration.course')),
                ('minor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.minor')),
            ],
        ),
        migrations.CreateModel(
            name='MajorDegreeRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits_required', models.IntegerField()),
                ('courses', models.ManyToManyField(blank=True, related_name='major_courses', to='registration.course')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.major')),
            ],
        ),
    ]
