# Generated by Django 4.2.5 on 2023-11-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_alter_faculty_specialty_minordegreerequirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_fulltime',
            name='num_of_courses',
            field=models.IntegerField(default=0),
        ),
    ]
