# Generated by Django 4.2.5 on 2023-12-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='time_commitment',
            field=models.CharField(blank=True, default='100%', max_length=50, null=True),
        ),
    ]
