# Generated by Django 4.2.5 on 2023-12-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_faculty_time_commitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='add_drop_end_date',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='add_drop_start_date',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
    ]
