# Generated by Django 4.2.5 on 2023-12-16 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_semester_add_drop_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fac_advisor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.faculty'),
        ),
    ]
